# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('aspect', models.CharField(max_length=10)),
                ('comments', models.IntegerField()),
                ('positive', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('pos_list', models.CharField(max_length=100, null=True)),
                ('neg_list', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('aspect', models.CharField(max_length=10)),
                ('comments', models.IntegerField()),
                ('positive', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('pos_list', models.CharField(max_length=100, null=True)),
                ('neg_list', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
